// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/onboarding/v0/onboarding.proto

package onboarding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn   string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SetupLocationRequest) Reset() {
	*x = SetupLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupLocationRequest) ProtoMessage() {}

func (x *SetupLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupLocationRequest.ProtoReflect.Descriptor instead.
func (*SetupLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{0}
}

func (x *SetupLocationRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *SetupLocationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SetupLocationRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type SetupLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetupLocationResponse) Reset() {
	*x = SetupLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupLocationResponse) ProtoMessage() {}

func (x *SetupLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupLocationResponse.ProtoReflect.Descriptor instead.
func (*SetupLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{1}
}

type InstallerSetupLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn        string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Installer string `protobuf:"bytes,3,opt,name=installer,proto3" json:"installer,omitempty"`
}

func (x *InstallerSetupLocationRequest) Reset() {
	*x = InstallerSetupLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallerSetupLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerSetupLocationRequest) ProtoMessage() {}

func (x *InstallerSetupLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerSetupLocationRequest.ProtoReflect.Descriptor instead.
func (*InstallerSetupLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{2}
}

func (x *InstallerSetupLocationRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *InstallerSetupLocationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstallerSetupLocationRequest) GetInstaller() string {
	if x != nil {
		return x.Installer
	}
	return ""
}

type InstallerSetupLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimCode  string `protobuf:"bytes,1,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	LocationId int32  `protobuf:"varint,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
}

func (x *InstallerSetupLocationResponse) Reset() {
	*x = InstallerSetupLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallerSetupLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerSetupLocationResponse) ProtoMessage() {}

func (x *InstallerSetupLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerSetupLocationResponse.ProtoReflect.Descriptor instead.
func (*InstallerSetupLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{3}
}

func (x *InstallerSetupLocationResponse) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *InstallerSetupLocationResponse) GetLocationId() int32 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

type ClaimLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimCode string `protobuf:"bytes,1,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	User      string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *ClaimLocationRequest) Reset() {
	*x = ClaimLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLocationRequest) ProtoMessage() {}

func (x *ClaimLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLocationRequest.ProtoReflect.Descriptor instead.
func (*ClaimLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimLocationRequest) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *ClaimLocationRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ClaimLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClaimLocationResponse) Reset() {
	*x = ClaimLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLocationResponse) ProtoMessage() {}

func (x *ClaimLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLocationResponse.ProtoReflect.Descriptor instead.
func (*ClaimLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{5}
}

type SendClaimMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimCode string  `protobuf:"bytes,1,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	Email     string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Lang      *string `protobuf:"bytes,3,opt,name=lang,proto3,oneof" json:"lang,omitempty"`
}

func (x *SendClaimMailRequest) Reset() {
	*x = SendClaimMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendClaimMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendClaimMailRequest) ProtoMessage() {}

func (x *SendClaimMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendClaimMailRequest.ProtoReflect.Descriptor instead.
func (*SendClaimMailRequest) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{6}
}

func (x *SendClaimMailRequest) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *SendClaimMailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendClaimMailRequest) GetLang() string {
	if x != nil && x.Lang != nil {
		return *x.Lang
	}
	return ""
}

type SendClaimMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendClaimMailResponse) Reset() {
	*x = SendClaimMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendClaimMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendClaimMailResponse) ProtoMessage() {}

func (x *SendClaimMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendClaimMailResponse.ProtoReflect.Descriptor instead.
func (*SendClaimMailResponse) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{7}
}

type GetClaimCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn   string `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetClaimCodeRequest) Reset() {
	*x = GetClaimCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClaimCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimCodeRequest) ProtoMessage() {}

func (x *GetClaimCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimCodeRequest.ProtoReflect.Descriptor instead.
func (*GetClaimCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{8}
}

func (x *GetClaimCodeRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *GetClaimCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetClaimCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimCode  string `protobuf:"bytes,1,opt,name=claim_code,json=claimCode,proto3" json:"claim_code,omitempty"`
	LocationId string `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Claimed    bool   `protobuf:"varint,3,opt,name=claimed,proto3" json:"claimed,omitempty"`
	// claimed_at
	ClaimedBy   *string `protobuf:"bytes,5,opt,name=claimed_by,json=claimedBy,proto3,oneof" json:"claimed_by,omitempty"`
	GeneratedBy string  `protobuf:"bytes,6,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"` // valid_until
}

func (x *GetClaimCodeResponse) Reset() {
	*x = GetClaimCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClaimCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimCodeResponse) ProtoMessage() {}

func (x *GetClaimCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_onboarding_v0_onboarding_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimCodeResponse.ProtoReflect.Descriptor instead.
func (*GetClaimCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_onboarding_v0_onboarding_proto_rawDescGZIP(), []int{9}
}

func (x *GetClaimCodeResponse) GetClaimCode() string {
	if x != nil {
		return x.ClaimCode
	}
	return ""
}

func (x *GetClaimCodeResponse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetClaimCodeResponse) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *GetClaimCodeResponse) GetClaimedBy() string {
	if x != nil && x.ClaimedBy != nil {
		return *x.ClaimedBy
	}
	return ""
}

func (x *GetClaimCodeResponse) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

var File_proto_onboarding_v0_onboarding_proto protoreflect.FileDescriptor

var file_proto_onboarding_v0_onboarding_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x2f, 0x76, 0x30, 0x2f, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e,
	0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x22, 0x4e, 0x0a, 0x14, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x61, 0x0a, 0x1d, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x73, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x1e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x14, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6d, 0x0a, 0x14, 0x53,
	0x65, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x17, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6c, 0x61, 0x6e, 0x67, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x73, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xc6,
	0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65,
	0x64, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64,
	0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x32, 0x98, 0x04, 0x0a, 0x0a, 0x4f, 0x6e, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x62, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e,
	0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7d, 0x0a, 0x16, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x65, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79,
	0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0d, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x68, 0x61, 0x72,
	0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x27,
	0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e,
	0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e,
	0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x26, 0x2e, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72,
	0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x68, 0x61, 0x72, 0x6d,
	0x6f, 0x6e, 0x79, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x30, 0x3b, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_onboarding_v0_onboarding_proto_rawDescOnce sync.Once
	file_proto_onboarding_v0_onboarding_proto_rawDescData = file_proto_onboarding_v0_onboarding_proto_rawDesc
)

func file_proto_onboarding_v0_onboarding_proto_rawDescGZIP() []byte {
	file_proto_onboarding_v0_onboarding_proto_rawDescOnce.Do(func() {
		file_proto_onboarding_v0_onboarding_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_onboarding_v0_onboarding_proto_rawDescData)
	})
	return file_proto_onboarding_v0_onboarding_proto_rawDescData
}

var file_proto_onboarding_v0_onboarding_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_onboarding_v0_onboarding_proto_goTypes = []interface{}{
	(*SetupLocationRequest)(nil),           // 0: harmony.energy.v0.SetupLocationRequest
	(*SetupLocationResponse)(nil),          // 1: harmony.energy.v0.SetupLocationResponse
	(*InstallerSetupLocationRequest)(nil),  // 2: harmony.energy.v0.InstallerSetupLocationRequest
	(*InstallerSetupLocationResponse)(nil), // 3: harmony.energy.v0.InstallerSetupLocationResponse
	(*ClaimLocationRequest)(nil),           // 4: harmony.energy.v0.ClaimLocationRequest
	(*ClaimLocationResponse)(nil),          // 5: harmony.energy.v0.ClaimLocationResponse
	(*SendClaimMailRequest)(nil),           // 6: harmony.energy.v0.SendClaimMailRequest
	(*SendClaimMailResponse)(nil),          // 7: harmony.energy.v0.SendClaimMailResponse
	(*GetClaimCodeRequest)(nil),            // 8: harmony.energy.v0.GetClaimCodeRequest
	(*GetClaimCodeResponse)(nil),           // 9: harmony.energy.v0.GetClaimCodeResponse
}
var file_proto_onboarding_v0_onboarding_proto_depIdxs = []int32{
	0, // 0: harmony.energy.v0.Onboarding.SetupLocation:input_type -> harmony.energy.v0.SetupLocationRequest
	2, // 1: harmony.energy.v0.Onboarding.InstallerSetupLocation:input_type -> harmony.energy.v0.InstallerSetupLocationRequest
	4, // 2: harmony.energy.v0.Onboarding.ClaimLocation:input_type -> harmony.energy.v0.ClaimLocationRequest
	6, // 3: harmony.energy.v0.Onboarding.SendClaimMail:input_type -> harmony.energy.v0.SendClaimMailRequest
	8, // 4: harmony.energy.v0.Onboarding.GetClaimCode:input_type -> harmony.energy.v0.GetClaimCodeRequest
	1, // 5: harmony.energy.v0.Onboarding.SetupLocation:output_type -> harmony.energy.v0.SetupLocationResponse
	3, // 6: harmony.energy.v0.Onboarding.InstallerSetupLocation:output_type -> harmony.energy.v0.InstallerSetupLocationResponse
	5, // 7: harmony.energy.v0.Onboarding.ClaimLocation:output_type -> harmony.energy.v0.ClaimLocationResponse
	7, // 8: harmony.energy.v0.Onboarding.SendClaimMail:output_type -> harmony.energy.v0.SendClaimMailResponse
	9, // 9: harmony.energy.v0.Onboarding.GetClaimCode:output_type -> harmony.energy.v0.GetClaimCodeResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_onboarding_v0_onboarding_proto_init() }
func file_proto_onboarding_v0_onboarding_proto_init() {
	if File_proto_onboarding_v0_onboarding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_onboarding_v0_onboarding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallerSetupLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallerSetupLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendClaimMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendClaimMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClaimCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_onboarding_v0_onboarding_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClaimCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_onboarding_v0_onboarding_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_proto_onboarding_v0_onboarding_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_onboarding_v0_onboarding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_onboarding_v0_onboarding_proto_goTypes,
		DependencyIndexes: file_proto_onboarding_v0_onboarding_proto_depIdxs,
		MessageInfos:      file_proto_onboarding_v0_onboarding_proto_msgTypes,
	}.Build()
	File_proto_onboarding_v0_onboarding_proto = out.File
	file_proto_onboarding_v0_onboarding_proto_rawDesc = nil
	file_proto_onboarding_v0_onboarding_proto_goTypes = nil
	file_proto_onboarding_v0_onboarding_proto_depIdxs = nil
}
